spring.application.name=news-aggregator
server.port=9081

### NewsApi
#news.api.url=http://localhost:9080
news.api.url=https://newsapi.org/v2
#news.api.key=1234
news.api.key=c544d0acd2a44f4d8fd11ca96f4f7153