spring.application.name=news-aggregator
server.port=9081

###
breaking.news.hours=24
negative.sentiment.threshold=0.6
diverse.viewpoints.threshold=0.3
limited.source.diversity.threshold=3.0

### NewsApi
#news.api.url=http://localhost:9080
news.api.url=https://newsapi.org/v2
news.api.key=1234
news.api.page-size=100