# This workflow will build a React project with npm

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build React App and push to ACR

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - 'news-aggregator-app/**'
env:
  ACR_LOGIN_SERVER: 'newsaggregator.azurecr.io'
  IMAGE_NAME: 'news-aggregator-microservice' 

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Log in to Azure Container Registry
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        registry: ${{ env.ACR_LOGIN_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
        
    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      with:
        images: ${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}
        
    - name: Install dependencies
      run: npm install
      working-directory: ./news-aggregator-app/
        
    - name: Build with npm
      run: npm run build
      working-directory: ./news-aggregator-app/
        
    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
      with:
        context: ./news-aggregator-app/
        file: ./news-aggregator-app/Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
